services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    environment:
      - SQL_DB=${SQL_DB}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_net
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SQL_DB=${SQL_DB}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception_net
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/wordpress:ro
    networks:
      - inception_net
    restart: always

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/adoireau/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/adoireau/data/wordpress

networks:
  inception_net:
    name: inception_net
    driver: bridge
